schema_version = "1.0.0"
id = "SHIRAKUMO_rectangle_tools"
name = "Rectangle Tools"
version = "1.0.0"
tagline = "Tools to more easily draw rectangles in edit mode"
maintainer = "Yukari Hafner"
type = "add-on"
tags = ["Modeling"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later","SPDX:Zlib"]
website = "https://shirakumo.org/projects/blender-rectangle-tools"
copyright = ["2025 Yukari Hafner"]
